### ISSUE TITLE
请问可以附一下运行方法吗？

### ISSUE THREAD

**Issue by ghost** [yuannancheng/tiku#1]
请问可以附一下这个项目的启动方法吗？我也有点自己的题库需要刷一下，想借用一下您的项目

**Comment by yuannancheng** [comment]
抱歉这么晚回复，晚点我会重新写一个更详细点的readme，来介绍如何使用。

**Comment by yuannancheng** [comment]
您好，更详细的说明文档已经上传，如果有需要可以参考使用：<https://github.com/yuannancheng/tiku/blob/master/README.md>
